GRANT SELECT, INSERT, UPDATE ON SANPHAM TO GiamDoc;
GRANT SELECT, INSERT, UPDATE ON TONKHO TO GiamDoc;
GRANT SELECT, INSERT, UPDATE ON HOADON TO GiamDoc;
GRANT SELECT, INSERT, UPDATE ON CTHD TO   GiamDoc;
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO GiamDoc;
GRANT SELECT, INSERT, UPDATE ON NHANVIEN_PUBLIC TO GiamDoc;
GRANT SELECT, INSERT, UPDATE ON NHANVIEN_PRIVATE TO GiamDoc;
GRANT SELECT, INSERT, UPDATE ON CHINHANH TO GiamDoc;

GRANT SELECT, INSERT, UPDATE ON SANPHAM TO QuanLy1;
GRANT SELECT, INSERT, UPDATE ON TONKHO TO QuanLy1;
GRANT SELECT, INSERT, UPDATE ON HOADON TO QuanLy1;
GRANT SELECT, INSERT, UPDATE ON CTHD TO QuanLy1;
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO QuanLy1;
GRANT SELECT ON NHANVIEN_PUBLIC TO QuanLy1;
GRANT SELECT ON NHANVIEN_PRIVATE TO QuanLy1;

GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO NhanVien1;
GRANT SELECT, INSERT, UPDATE ON HOADON TO NhanVien1;
GRANT SELECT, INSERT, UPDATE ON CTHD TO NhanVien1;
GRANT SELECT ON SANPHAM TO NhanVien1;
GRANT SELECT ON TONKHO TO NhanVien1;


CREATE USER QuanLy2 IDENTIFIED BY quanly2;
CREATE USER QuanLy3 IDENTIFIED BY quanly3;
CREATE USER NhanVien2 IDENTIFIED BY nhanvien2;
CREATE USER NhanVien3 IDENTIFIED BY nhanvien3;
GRANT CONNECT TO QuanLy2, QuanLy3, NhanVien2, NhanVien3;
GRANT SELECT ON NHANVIEN_PUBLIC TO QuanLy2, QuanLy3;
GRANT SELECT ON TONKHO TO NhanVien2, NhanVien3;


-- BẢNG CHI NHÁNH
CREATE TABLE CHINHANH (
  MACHINHANH VARCHAR2(10) PRIMARY KEY,
  TENCHINHANH VARCHAR2(100),
  DIACHI VARCHAR2(200),
  SODIENTHOAI VARCHAR2(20)
);

-- BẢNG NHÂN VIÊN CÔNG KHAI (Public Info)
CREATE TABLE NHANVIEN_PUBLIC (
  MANV VARCHAR2(10) PRIMARY KEY,
  HOTEN VARCHAR2(100),
  GIOITINH VARCHAR2(10),
  NGAYSINH DATE,
  DIACHI VARCHAR2(200),
  SODIENTHOAI VARCHAR2(15),
  NGAYVAOLAM DATE,
  CHUCVU VARCHAR2(50),
  MACHINHANH VARCHAR2(10),
  ISDELETE NUMBER(1) DEFAULT 0 CHECK (ISDELETE IN (0,1)),
  CONSTRAINT FK_NV_PUBLIC_CN FOREIGN KEY (MACHINHANH) REFERENCES CHINHANH(MACHINHANH)
);

-- BẢNG NHÂN VIÊN RIÊNG (Private Info)
CREATE TABLE NHANVIEN_PRIVATE (
  MANV VARCHAR2(10) PRIMARY KEY,
  LUONG NUMBER,
  MACHINHANH VARCHAR2(10),         
  ISDELETE NUMBER(1) DEFAULT 0 CHECK (ISDELETE IN (0,1)),
  CONSTRAINT FK_NV_PRIVATE_PUBLIC FOREIGN KEY (MANV) REFERENCES NHANVIEN_PUBLIC(MANV)
);

-- BẢNG KHÁCH HÀNG
CREATE TABLE KHACHHANG (
  MAKH VARCHAR2(10) PRIMARY KEY,
  HOTEN VARCHAR2(100),
  DIACHI VARCHAR2(200),
  SODIENTHOAI VARCHAR2(20),
  TONGTIEN NUMBER DEFAULT 0,
  ISDELETE NUMBER(1) DEFAULT 0 CHECK (ISDELETE IN (0,1))
);

-- BẢNG SẢN PHẨM
CREATE TABLE SANPHAM (
  MASP VARCHAR2(10) PRIMARY KEY,
  TENSANPHAM VARCHAR2(200),
  DANHMUC VARCHAR2(50),
  THUONGHIEU VARCHAR2(50),
  GIANHAP NUMBER,
  GIABAN NUMBER,
  ISDELETE NUMBER(1) DEFAULT 0 CHECK (ISDELETE IN (0,1))
);

-- BẢNG TỒN KHO
CREATE TABLE TONKHO (
  MASP VARCHAR2(10),
  MACHINHANH VARCHAR2(10),
  SOLUONG NUMBER,
  TINHTRANG VARCHAR2(20), -- 'Còn Hàng' hoặc 'Hết Hàng'
  NGAYCAPNHAT DATE,
  PRIMARY KEY (MASP, MACHINHANH),
  CONSTRAINT FK_TK_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
  CONSTRAINT FK_TK_CN FOREIGN KEY (MACHINHANH) REFERENCES CHINHANH(MACHINHANH)
);

-- BẢNG HÓA ĐƠN
CREATE TABLE HOADON (
  MAHD VARCHAR2(10) PRIMARY KEY,
  MANV VARCHAR2(10),
  MAKH VARCHAR2(10),
  NGAYTAO DATE,
  TONGTIEN NUMBER,
  ISDELETE NUMBER(1) DEFAULT 0 CHECK (ISDELETE IN (0,1)),
  CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN_PUBLIC(MANV),
  CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- BẢNG CHI TIẾT HÓA ĐƠN
CREATE TABLE CTHD (
  MAHD VARCHAR2(10),
  MASP VARCHAR2(10),
  SOLUONG NUMBER,
  ISDELETE NUMBER(1) DEFAULT 0 CHECK (ISDELETE IN (0,1)),
  PRIMARY KEY (MAHD, MASP),
  CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
  CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);


-- Thêm dữ liệu vào bảng CHINHANH
INSERT INTO CHINHANH (MACHINHANH, TENCHINHANH, DIACHI, SODIENTHOAI) VALUES
  ('CN1', 'Chi nhánh TP.HCM', '123 Lê Lợi, Quận 1, TP.HCM', '02812345678');

COMMIT;


CREATE PUBLIC DATABASE LINK CN2_GiamDoc CONNECT TO GiamDoc IDENTIFIED BY giamdoc USING 'long_link';
CREATE PUBLIC DATABASE LINK CN2_QuanLy1 CONNECT TO QuanLy2 IDENTIFIED BY quanly2 USING 'long_link';
CREATE PUBLIC DATABASE LINK CN2_NhanVien1 CONNECT TO NhanVien2 IDENTIFIED BY nhanvien2 USING 'long_link';

CREATE PUBLIC DATABASE LINK CN3_GiamDoc CONNECT TO GiamDoc IDENTIFIED BY giamdoc USING 'pnl_link';
CREATE PUBLIC DATABASE LINK CN3_QuanLy1 CONNECT TO QuanLy1 IDENTIFIED BY quanly1 USING 'pnl_link';
CREATE PUBLIC DATABASE LINK CN3_NhanVien1 CONNECT TO NhanVien3 IDENTIFIED BY nhanvien3 USING 'pnl_link';

COMMIT;


/*====================================================================== THỰC HIỆN CÂU TRUY VẤN =================================================================================================*/
--- CÂU 1
SELECT MACHINHANH, MANV, HOTEN, DOANHTHUCANHAN
FROM (
SELECT MACHINHANH, N.MANV, N.HOTEN, SUM(H.TONGTIEN) AS DOANHTHUCANHAN
FROM CN1.NHANVIEN_PUBLIC N
JOIN CN1.HOADON H ON N.MANV = H.MANV
WHERE H.ISDELETE = 0 AND EXTRACT(YEAR FROM H.NGAYTAO) = 2024
GROUP BY N.MACHINHANH, N.MANV, N.HOTEN
ORDER BY SUM(H.TONGTIEN) DESC
FETCH FIRST 1 ROW WITH TIES
)
UNION ALL
SELECT MACHINHANH, MANV, HOTEN, DOANHTHUCANHAN
FROM (
SELECT MACHINHANH, N.MANV, N.HOTEN, SUM(H.TONGTIEN) AS DOANHTHUCANHAN
FROM CN2.NHANVIEN_PUBLIC@CN2_GiamDoc N
JOIN CN2.HOADON@CN2_GiamDoc H ON N.MANV = H.MANV
WHERE H.ISDELETE = 0 AND EXTRACT(YEAR FROM H.NGAYTAO) = 2024
GROUP BY N.MACHINHANH, N.MANV, N.HOTEN
ORDER BY SUM(H.TONGTIEN) DESC
FETCH FIRST 1 ROW WITH TIES
)
UNION ALL
SELECT MACHINHANH, MANV, HOTEN, DOANHTHUCANHAN
FROM (
SELECT MACHINHANH, N.MANV, N.HOTEN, SUM(H.TONGTIEN) AS DOANHTHUCANHAN
FROM CN3.NHANVIEN_PUBLIC@CN3_GiamDoc N
JOIN CN3.HOADON@CN3_GiamDoc H ON N.MANV = H.MANV
WHERE H.ISDELETE = 0 AND EXTRACT(YEAR FROM H.NGAYTAO) = 2024
GROUP BY N.MACHINHANH, N.MANV, N.HOTEN
ORDER BY SUM(H.TONGTIEN) DESC
FETCH FIRST 1 ROW WITH TIES
);

 -- CÂU 2
 SELECT 
    NVL(MACHINHANH, 'TONG') AS MACHINHANH, 
    SUM(TONGTIEN) AS DOANHTHU
FROM (
    SELECT HD.MANV, NV.MACHINHANH, HD.TONGTIEN
    FROM CN1.HOADON HD
    JOIN CN1.NHANVIEN_PUBLIC NV ON HD.MANV = NV.MANV
    WHERE HD.ISDELETE = 0 AND EXTRACT(YEAR FROM HD.NGAYTAO) = 2024
    UNION ALL
    SELECT HD.MANV, NV.MACHINHANH, HD.TONGTIEN
    FROM CN2.HOADON@CN2_GiamDoc HD
    JOIN CN2.NHANVIEN_PUBLIC@CN2_GiamDoc NV ON HD.MANV = NV.MANV
    WHERE HD.ISDELETE = 0 AND EXTRACT(YEAR FROM HD.NGAYTAO) = 2024
    UNION ALL
    SELECT HD.MANV, NV.MACHINHANH, HD.TONGTIEN
    FROM CN3.HOADON@CN3_GiamDoc HD
    JOIN CN3.NHANVIEN_PUBLIC@CN3_GiamDoc NV ON HD.MANV = NV.MANV
    WHERE HD.ISDELETE = 0 AND EXTRACT(YEAR FROM HD.NGAYTAO) = 2024
)
GROUP BY ROLLUP(MACHINHANH)


-- CÂU 3
SELECT MAKH, MASP, (SELECT TENSANPHAM FROM CN1.SANPHAM WHERE MASP = DS.MASP) AS TENSANPHAM
FROM (
  SELECT H.MAKH, C.MASP, NV.MACHINHANH
  FROM CN1.HOADON H
  JOIN CN1.CTHD C ON H.MAHD = C.MAHD
  JOIN CN1.NHANVIEN_PUBLIC NV ON H.MANV = NV.MANV
  WHERE H.ISDELETE = 0 AND C.ISDELETE = 0
  UNION ALL
  SELECT H.MAKH, C.MASP, NV.MACHINHANH
  FROM CN2.HOADON@CN2_GiamDoc H
  JOIN CN2.CTHD@CN2_GiamDoc C ON H.MAHD = C.MAHD
  JOIN CN2.NHANVIEN_PUBLIC@CN2_GiamDoc NV ON H.MANV = NV.MANV
  WHERE H.ISDELETE = 0 AND C.ISDELETE = 0
  UNION ALL
  SELECT H.MAKH, C.MASP, NV.MACHINHANH
  FROM CN3.HOADON@CN3_GiamDoc H
  JOIN CN3.CTHD@CN3_GiamDoc C ON H.MAHD = C.MAHD
  JOIN CN3.NHANVIEN_PUBLIC@CN3_GiamDoc NV ON H.MANV = NV.MANV
  WHERE H.ISDELETE = 0 AND C.ISDELETE = 0
) DS
GROUP BY MAKH, MASP
HAVING COUNT(DISTINCT MACHINHANH) >= 2;


--- CÂU 4
SELECT MACHINHANH, ROUND(AVG(LUONG), 0) AS LUONG_TRUNG_BINH
FROM (
  SELECT MACHINHANH, LUONG 
  FROM CN1.NHANVIEN_PRIVATE 
  WHERE ISDELETE = 0
  UNION ALL
  SELECT MACHINHANH, LUONG 
  FROM CN2.NHANVIEN_PRIVATE@CN2_GiamDoc 
  WHERE ISDELETE = 0
  UNION ALL
  SELECT MACHINHANH, LUONG 
  FROM CN3.NHANVIEN_PRIVATE@CN3_GiamDoc 
  WHERE ISDELETE = 0
)
GROUP BY MACHINHANH
ORDER BY MACHINHANH;



/*====================================================================== FUNCTION - PROCEDURE - TRIGGER =================================================================================================*/

--------------------------- FUNCTION ----------------------------------
CREATE OR REPLACE FUNCTION ThongKeMuaHangKhachHang(p_makh IN VARCHAR2)
RETURN NUMBER
IS
  v_count_cn1 NUMBER := 0;
  v_sum_cn1   NUMBER := 0;
  v_count_cn2 NUMBER := 0;
  v_sum_cn2   NUMBER := 0;
  v_count_cn3 NUMBER := 0;
  v_sum_cn3   NUMBER := 0;
  v_total_hd  NUMBER := 0;
  v_total_tien NUMBER := 0;
BEGIN
  -- CN1(local)
  BEGIN
    SELECT COUNT(*), NVL(SUM(TONGTIEN), 0)
    INTO v_count_cn1, v_sum_cn1
    FROM CN1.HOADON
    WHERE MAKH = p_makh AND ISDELETE = 0;
  EXCEPTION
    WHEN OTHERS THEN
      v_count_cn1 := 0;
      v_sum_cn1 := 0;
  END;

  -- CN2
  BEGIN
    SELECT COUNT(*), NVL(SUM(TONGTIEN), 0)
    INTO v_count_cn2, v_sum_cn2
    FROM CN2.HOADON@CN2_GiamDoc
    WHERE MAKH = p_makh AND ISDELETE = 0;
  EXCEPTION
    WHEN OTHERS THEN
      v_count_cn2 := 0;
      v_sum_cn2 := 0;
  END;

  -- CN3
  BEGIN
    SELECT COUNT(*), NVL(SUM(TONGTIEN), 0)
    INTO v_count_cn3, v_sum_cn3
    FROM CN3.HOADON@CN3_GiamDoc
    WHERE MAKH = p_makh AND ISDELETE = 0;
  EXCEPTION
    WHEN OTHERS THEN
      v_count_cn3 := 0;
      v_sum_cn3 := 0;
  END;

  -- Tổng
  v_total_hd := v_count_cn1 + v_count_cn2 + v_count_cn3;
  v_total_tien := v_sum_cn1 + v_sum_cn2 + v_sum_cn3;

  -- In kết quả
  DBMS_OUTPUT.PUT_LINE('--- THỐNG KÊ CHO KHÁCH HÀNG: ' || p_makh || ' ---');
  DBMS_OUTPUT.PUT_LINE('CN1: ' || v_count_cn1 || ' hóa đơn - ' || TO_CHAR(v_sum_cn1, 'FM999G999G999G999G999') || ' VNĐ');
  DBMS_OUTPUT.PUT_LINE('CN2: ' || v_count_cn2 || ' hóa đơn - ' || TO_CHAR(v_sum_cn2, 'FM999G999G999') || ' VNĐ');
  DBMS_OUTPUT.PUT_LINE('CN3: ' || v_count_cn3 || ' hóa đơn - ' || TO_CHAR(v_sum_cn3, 'FM999G999G999') || ' VNĐ');
  DBMS_OUTPUT.PUT_LINE('=> TỔNG: ' || v_total_hd || ' hóa đơn - ' || TO_CHAR(v_total_tien, 'FM999G999G999G999G999') || ' VNĐ');

  RETURN v_total_tien;
END;

SET SERVEROUTPUT ON; 
DECLARE
  tong_tien NUMBER;
BEGIN
  tong_tien := ThongKeMuaHangKhachHang('KH0001');
  DBMS_OUTPUT.PUT_LINE('Tổng tiền trả về từ function: ' || TO_CHAR(tong_tien, 'FM999G999G999G999G999') || ' VNĐ');
END;
/
COMMIT;


--------------------------------------------------- PROCEDURE ---------------------------------------------------------------
CREATE OR REPLACE PROCEDURE DongBoKhachHang(
  p_makh        IN VARCHAR2,
  p_hoten       IN VARCHAR2,
  p_diachi      IN VARCHAR2,
  p_sdt         IN VARCHAR2,
  p_tongtien    IN NUMBER DEFAULT 0
)
IS
  v_exists NUMBER := 0;
BEGIN
  -- Chèn vào local (CN đang gọi)
  SELECT COUNT(*) INTO v_exists FROM KHACHHANG WHERE MAKH = p_makh;
  IF v_exists = 0 THEN
    INSERT INTO KHACHHANG(MAKH, HOTEN, DIACHI, SODIENTHOAI, TONGTIEN, ISDELETE)
    VALUES (p_makh, p_hoten, p_diachi, p_sdt, p_tongtien, 0);
    DBMS_OUTPUT.PUT_LINE('Đã thêm vào chi nhánh hiện tại');
  END IF;
 
  -- Chèn vào CN2 nếu chưa có
  BEGIN
    SELECT COUNT(*) INTO v_exists FROM CN2.KHACHHANG@CN2_GiamDoc WHERE MAKH = p_makh;
    IF v_exists = 0 THEN
      INSERT INTO CN2.KHACHHANG@CN2_GiamDoc(MAKH, HOTEN, DIACHI, SODIENTHOAI, TONGTIEN, ISDELETE)
      VALUES (p_makh, p_hoten, p_diachi, p_sdt, p_tongtien, 0);
      DBMS_OUTPUT.PUT_LINE('Đồng bộ vào CN2');
    END IF;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Không thể chèn vào CN2 (có thể đã tồn tại hoặc lỗi kết nối)');
  END;
 
  -- Chèn vào CN3 nếu chưa có
  BEGIN
    SELECT COUNT(*) INTO v_exists FROM CN3.KHACHHANG@CN3_GiamDoc WHERE MAKH = p_makh;
    IF v_exists = 0 THEN
      INSERT INTO CN3.KHACHHANG@CN3_GiamDoc(MAKH, HOTEN, DIACHI, SODIENTHOAI, TONGTIEN, ISDELETE)
      VALUES (p_makh, p_hoten, p_diachi, p_sdt, p_tongtien, 0);
      DBMS_OUTPUT.PUT_LINE('Đồng bộ vào CN3');
    END IF;
  EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Không thể chèn vào CN3 (có thể đã tồn tại hoặc lỗi kết nối)');
  END;
 
  COMMIT;
END;
/

BEGIN
  DongBoKhachHang(
    p_makh     => 'KH1005',
    p_hoten    => 'HH',
    p_diachi   => 'HCM',
    p_sdt      => '0909009090',
    p_tongtien => 0
  );
END;
/

SELECT * FROM CN1.KHACHHANG WHERE MAKH='KH1004'


----------------------------------------------------------------------------- TRIGGER ------------------------------------------------------------------
CREATE OR REPLACE TRIGGER check_inventory_before_selling
BEFORE INSERT ON CTHD
FOR EACH ROW
DECLARE
  v_soluong_tonkho TONKHO.SOLUONG%TYPE;
  v_machinhanh NHANVIEN_PUBLIC.MACHINHANH%TYPE;
BEGIN
  SELECT MACHINHANH INTO v_machinhanh
  FROM HOADON H JOIN NHANVIEN_PUBLIC NV ON H.MANV = NV.MANV
  WHERE H.MAHD = :NEW.MAHD;
  SELECT SOLUONG INTO v_soluong_tonkho
  FROM TONKHO
  WHERE MASP = :NEW.MASP AND MACHINHANH = v_machinhanh;
  IF v_soluong_tonkho < :NEW.SOLUONG THEN
    RAISE_APPLICATION_ERROR(-20001, 'Số lượng tồn kho không đủ để bán.');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20002, 'Không tìm thấy sản phẩm trong tồn kho tại chi nhánh.');
END;