---- INDEXING IN ORACLE
SET TIMING ON;
COMMIT;

EXPLAIN PLAN FOR
SELECT * FROM (
  SELECT KH.MAKH, KH.HOTEN, H.NGAYTAO, SP.TENSANPHAM
  FROM CN1.HOADON H
  JOIN CN1.CTHD C ON H.MAHD = C.MAHD
  JOIN CN1.SANPHAM SP ON C.MASP = SP.MASP
  JOIN CN1.KHACHHANG KH ON KH.MAKH = H.MAKH
  WHERE H.ISDELETE = 0 AND SP.THUONGHIEU = 'Yonex' AND EXTRACT(YEAR FROM H.NGAYTAO) = 2024

  UNION ALL

  SELECT KH.MAKH, KH.HOTEN, H.NGAYTAO, SP.TENSANPHAM
  FROM CN2.HOADON@CN2_GiamDoc H
  JOIN CN2.CTHD@CN2_GiamDoc C ON H.MAHD = C.MAHD
  JOIN CN2.SANPHAM@CN2_GiamDoc SP ON C.MASP = SP.MASP
  JOIN CN2.KHACHHANG@CN2_GiamDoc KH ON KH.MAKH = H.MAKH
  WHERE H.ISDELETE = 0 AND SP.THUONGHIEU = 'Yonex' AND EXTRACT(YEAR FROM H.NGAYTAO) = 2024

  UNION ALL

  SELECT KH.MAKH, KH.HOTEN, H.NGAYTAO, SP.TENSANPHAM
  FROM CN3.HOADON@CN3_GiamDoc H
  JOIN CN3.CTHD@CN3_GiamDoc C ON H.MAHD = C.MAHD
  JOIN CN3.SANPHAM@CN3_GiamDoc SP ON C.MASP = SP.MASP
  JOIN CN3.KHACHHANG@CN3_GiamDoc KH ON KH.MAKH = H.MAKH
  WHERE H.ISDELETE = 0 AND SP.THUONGHIEU = 'Yonex' AND EXTRACT(YEAR FROM H.NGAYTAO) = 2024
);


SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());



--------------------TẠO INDEX
--  Function-Based &  Composite Index
CREATE INDEX IDX_HD_YEAR_DELETE ON HOADON(ISDELETE, EXTRACT(YEAR FROM NGAYTAO));

--  B-tree Index trên một cột
CREATE INDEX IDX_HOADON_MAKH ON HOADON(MAKH);

--  Composite B-tree Index (Covering Index)
CREATE INDEX IDX_SP_THUONGHIEU_COVER ON SANPHAM(THUONGHIEU, MASP, TENSANPHAM);




